#############################################################################
# Makefile for building: rt4sv++
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sat Sep 24 01:46:16 2022
# Project:  ui_class.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile ui_class.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -std=c++11 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++11 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/local/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L /usr/local/lib/ -lCCfits -lcfitsio -L/usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats -lqsvg -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = UI/varcoefscalcwidget.cpp \
		body.cpp \
		data/calibration.cpp \
		data/exportvaroiusdata.cpp \
		data/spectral_container.cpp \
		libs/qcustomplot.cpp \
		main.cpp \
		data/averovervelocity.cpp \
		data/integrate.cpp \
		data/averovertime.cpp \
		data/wd.cpp \
		data/spectralindex.cpp \
		data/rotation.cpp \
		data/savespectrumtoascii.cpp \
		UI/vbox_main.cpp \
		UI/integrate_widget.cpp \
		UI/export_dynamic_spectrum_widget.cpp \
		UI/calsection.cpp \
		UI/heat_map_widget.cpp \
		UI/single_spec_widget.cpp \
		UI/rms_sec_widget.cpp \
		UI/rms_selector.cpp \
		data/extractlcs.cpp moc_varcoefscalcwidget.cpp \
		moc_body.cpp \
		moc_qcustomplot.cpp \
		moc_heat_map_widget.cpp \
		moc_single_spec_widget.cpp \
		moc_rms_sec_widget.cpp \
		moc_rms_selector.cpp \
		qrc_resources.cpp
OBJECTS       = varcoefscalcwidget.o \
		body.o \
		calibration.o \
		exportvaroiusdata.o \
		spectral_container.o \
		qcustomplot.o \
		main.o \
		averovervelocity.o \
		integrate.o \
		averovertime.o \
		wd.o \
		spectralindex.o \
		rotation.o \
		savespectrumtoascii.o \
		vbox_main.o \
		integrate_widget.o \
		export_dynamic_spectrum_widget.o \
		calsection.o \
		heat_map_widget.o \
		single_spec_widget.o \
		rms_sec_widget.o \
		rms_selector.o \
		extractlcs.o \
		moc_varcoefscalcwidget.o \
		moc_body.o \
		moc_qcustomplot.o \
		moc_heat_map_widget.o \
		moc_single_spec_widget.o \
		moc_rms_sec_widget.o \
		moc_rms_selector.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ui_class.pro
QMAKE_TARGET  = rt4sv++
DESTDIR       = 
TARGET        = rt4sv++

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ui_class.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile ui_class.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ui_class.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/rt4sv++1.0.0 || $(MKDIR) .tmp/rt4sv++1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/rt4sv++1.0.0/ && $(COPY_FILE) --parents UI/varcoefscalcwidget.h body.h data/spectral_container.h libs/qcustomplot.h UI/vbox_main.h UI/integrate_widget.h UI/export_dynamic_spectrum_widget.h UI/calsection.h UI/heat_map_widget.h UI/single_spec_widget.h UI/rms_sec_widget.h UI/rms_selector.h .tmp/rt4sv++1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/rt4sv++1.0.0/ && $(COPY_FILE) --parents UI/varcoefscalcwidget.cpp body.cpp data/calibration.cpp data/exportvaroiusdata.cpp data/spectral_container.cpp libs/qcustomplot.cpp main.cpp data/averovervelocity.cpp data/integrate.cpp data/averovertime.cpp data/wd.cpp data/spectralindex.cpp data/rotation.cpp data/savespectrumtoascii.cpp UI/vbox_main.cpp UI/integrate_widget.cpp UI/export_dynamic_spectrum_widget.cpp UI/calsection.cpp UI/heat_map_widget.cpp UI/single_spec_widget.cpp UI/rms_sec_widget.cpp UI/rms_selector.cpp data/extractlcs.cpp .tmp/rt4sv++1.0.0/ && (cd `dirname .tmp/rt4sv++1.0.0` && $(TAR) rt4sv++1.0.0.tar rt4sv++1.0.0 && $(COMPRESS) rt4sv++1.0.0.tar) && $(MOVE) `dirname .tmp/rt4sv++1.0.0`/rt4sv++1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/rt4sv++1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_varcoefscalcwidget.cpp moc_body.cpp moc_qcustomplot.cpp moc_heat_map_widget.cpp moc_single_spec_widget.cpp moc_rms_sec_widget.cpp moc_rms_selector.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_varcoefscalcwidget.cpp moc_body.cpp moc_qcustomplot.cpp moc_heat_map_widget.cpp moc_single_spec_widget.cpp moc_rms_sec_widget.cpp moc_rms_selector.cpp
moc_varcoefscalcwidget.cpp: UI/varcoefscalcwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UI/varcoefscalcwidget.h -o moc_varcoefscalcwidget.cpp

moc_body.cpp: libs/qcustomplot.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h \
		data/spectral_container.h \
		UI/vbox_main.h \
		UI/integrate_widget.h \
		UI/export_dynamic_spectrum_widget.h \
		UI/calsection.h \
		UI/heat_map_widget.h \
		UI/single_spec_widget.h \
		UI/rms_sec_widget.h \
		UI/varcoefscalcwidget.h \
		UI/rms_selector.h \
		body.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) body.h -o moc_body.cpp

moc_qcustomplot.cpp: libs/qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) libs/qcustomplot.h -o moc_qcustomplot.cpp

moc_heat_map_widget.cpp: libs/qcustomplot.h \
		data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h \
		UI/heat_map_widget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UI/heat_map_widget.h -o moc_heat_map_widget.cpp

moc_single_spec_widget.cpp: data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h \
		libs/qcustomplot.h \
		UI/single_spec_widget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UI/single_spec_widget.h -o moc_single_spec_widget.cpp

moc_rms_sec_widget.cpp: libs/qcustomplot.h \
		data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h \
		UI/rms_sec_widget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UI/rms_sec_widget.h -o moc_rms_sec_widget.cpp

moc_rms_selector.cpp: UI/rms_selector.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UI/rms_selector.h -o moc_rms_selector.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		images/RIGHTicon.svg \
		images/integrateIcon.svg \
		images/openSingleSpecIcon.svg \
		images/LEFTicon.svg \
		images/calibrateIcon.svg \
		images/loadFitsFilesIcon.svg \
		images/deathstaradder.svg \
		images/averOverTimeIcon.svg \
		images/LHCDSicon.svg \
		images/exportDynspecIcon.svg \
		images/reloadIcon.svg \
		images/VDSicon.svg \
		images/RHDSicon.svg \
		images/FLAGicon.svg \
		images/openRmsSection.svg \
		images/Rotate_p_icon.svg \
		images/loadFitsAVRIcon.svg \
		images/chiRedIcon.svg \
		images/Rotate_m_icon.svg \
		images/UPicon.svg \
		images/averOverVelIcon.svg \
		images/DOWNicon.svg \
		images/exitIcon.svg \
		images/IDSicon2.svg \
		images/openDynSpecIcon.svg
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

varcoefscalcwidget.o: UI/varcoefscalcwidget.cpp UI/varcoefscalcwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o varcoefscalcwidget.o UI/varcoefscalcwidget.cpp

body.o: body.cpp /usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o body.o body.cpp

calibration.o: data/calibration.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibration.o data/calibration.cpp

exportvaroiusdata.o: data/exportvaroiusdata.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportvaroiusdata.o data/exportvaroiusdata.cpp

spectral_container.o: data/spectral_container.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectral_container.o data/spectral_container.cpp

qcustomplot.o: libs/qcustomplot.cpp libs/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o libs/qcustomplot.cpp

main.o: main.cpp body.h \
		libs/qcustomplot.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h \
		data/spectral_container.h \
		UI/vbox_main.h \
		UI/integrate_widget.h \
		UI/export_dynamic_spectrum_widget.h \
		UI/calsection.h \
		UI/heat_map_widget.h \
		UI/single_spec_widget.h \
		UI/rms_sec_widget.h \
		UI/varcoefscalcwidget.h \
		UI/rms_selector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

averovervelocity.o: data/averovervelocity.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o averovervelocity.o data/averovervelocity.cpp

integrate.o: data/integrate.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integrate.o data/integrate.cpp

averovertime.o: data/averovertime.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o averovertime.o data/averovertime.cpp

wd.o: data/wd.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wd.o data/wd.cpp

spectralindex.o: data/spectralindex.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectralindex.o data/spectralindex.cpp

rotation.o: data/rotation.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotation.o data/rotation.cpp

savespectrumtoascii.o: data/savespectrumtoascii.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savespectrumtoascii.o data/savespectrumtoascii.cpp

vbox_main.o: UI/vbox_main.cpp UI/vbox_main.h \
		UI/integrate_widget.h \
		data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vbox_main.o UI/vbox_main.cpp

integrate_widget.o: UI/integrate_widget.cpp UI/integrate_widget.h \
		data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integrate_widget.o UI/integrate_widget.cpp

export_dynamic_spectrum_widget.o: UI/export_dynamic_spectrum_widget.cpp UI/export_dynamic_spectrum_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o export_dynamic_spectrum_widget.o UI/export_dynamic_spectrum_widget.cpp

calsection.o: UI/calsection.cpp UI/calsection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calsection.o UI/calsection.cpp

heat_map_widget.o: UI/heat_map_widget.cpp UI/heat_map_widget.h \
		libs/qcustomplot.h \
		data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o heat_map_widget.o UI/heat_map_widget.cpp

single_spec_widget.o: UI/single_spec_widget.cpp UI/single_spec_widget.h \
		data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h \
		libs/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o single_spec_widget.o UI/single_spec_widget.cpp

rms_sec_widget.o: UI/rms_sec_widget.cpp UI/rms_sec_widget.h \
		libs/qcustomplot.h \
		data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rms_sec_widget.o UI/rms_sec_widget.cpp

rms_selector.o: UI/rms_selector.cpp UI/rms_selector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rms_selector.o UI/rms_selector.cpp

extractlcs.o: data/extractlcs.cpp data/spectral_container.h \
		/usr/local/include/CCfits/CCfits \
		/usr/local/include/CCfits/CCfits.h \
		/usr/local/include/fitsio.h \
		/usr/local/include/longnam.h \
		/usr/local/include/CCfits/FITS.h \
		/usr/local/include/CCfits/ExtHDU.h \
		/usr/local/include/CCfits/HDU.h \
		/usr/local/include/CCfits/Keyword.h \
		/usr/local/include/CCfits/FitsError.h \
		/usr/local/include/CCfits/NewKeyword.h \
		/usr/local/include/CCfits/KeywordCreator.h \
		/usr/local/include/CCfits/KeyData.h \
		/usr/local/include/CCfits/FITSUtil.h \
		/usr/local/include/CCfits/KeywordT.h \
		/usr/local/include/CCfits/HDUCreator.h \
		/usr/local/include/CCfits/BinTable.h \
		/usr/local/include/CCfits/Table.h \
		/usr/local/include/CCfits/AsciiTable.h \
		/usr/local/include/CCfits/ColumnVectorData.h \
		/usr/local/include/CCfits/Column.h \
		/usr/local/include/CCfits/ColumnData.h \
		/usr/local/include/CCfits/ColumnT.h \
		/usr/local/include/CCfits/ExtHDUT.h \
		/usr/local/include/CCfits/ImageExt.h \
		/usr/local/include/CCfits/Image.h \
		/usr/local/include/CCfits/FITSUtilT.h \
		/usr/local/include/CCfits/PHDUT.h \
		/usr/local/include/CCfits/PrimaryHDU.h \
		/usr/local/include/CCfits/PHDU.h \
		/usr/local/include/CCfits/GroupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o extractlcs.o data/extractlcs.cpp

moc_varcoefscalcwidget.o: moc_varcoefscalcwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_varcoefscalcwidget.o moc_varcoefscalcwidget.cpp

moc_body.o: moc_body.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_body.o moc_body.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_heat_map_widget.o: moc_heat_map_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_heat_map_widget.o moc_heat_map_widget.cpp

moc_single_spec_widget.o: moc_single_spec_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_single_spec_widget.o moc_single_spec_widget.cpp

moc_rms_sec_widget.o: moc_rms_sec_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rms_sec_widget.o moc_rms_sec_widget.cpp

moc_rms_selector.o: moc_rms_selector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rms_selector.o moc_rms_selector.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

